# Generated by Django 6.0.7 on 2026-07-19 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_issued', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted')], default='pending', max_length=10)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='groups.membership')),
            ],
        ),
    ]
