# Generated by Django 6.0.7 on 2026-07-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_repayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
